### ISSUE TITLE
AttributeError: 'UserObject' object has no attribute 'lower'

### ISSUE THREAD

**Issue by sfc-gh-tlarkin** [secmerc/materialize-threats#10]
Running this against my draw.io file I get this output:

```
./materialize-threats --diagram=/Users/tlarkin/Documents/casec\ stuff/casec-1611/dfd.drawio 
Traceback (most recent call last):
  File "./materialize-threats", line 8, in <module>
    sys.exit(ThreatMaterializer.materialize())
  File "/Users/tlarkin/material-threats/env/lib/python3.8/site-packages/materialize_threats/materialize.py", line 116, in materialize
    zones = dbgraph.get_node_trust_zones_from_graph(graph)
  File "/Users/tlarkin/material-threats/env/lib/python3.8/site-packages/materialize_threats/db/dbgraph.py", line 43, in get_node_trust_zones_from_graph
    zone = UserObject.get_trust_zone_from_node_label(orphan.value)
  File "/Users/tlarkin/material-threats/env/lib/python3.8/site-packages/materialize_threats/mx/models/UserObject.py", line 33, in get_trust_zone_from_node_label
    zone = label.lower().split(cls.ZONE_PREFIX)[cls.ZONE_INDEX]
AttributeError: 'UserObject' object has no attribute 'lower'
```
My Python venv:
```
% python3 -V
Python 3.8.5
% pip3 list
Package             Version
------------------- -------
attrs               20.2.0
gherkin-official    4.1.3
iniconfig           1.0.1
materialize-threats 1.0.4
packaging           20.4
peewee              3.13.3
pip                 20.1.1
pluggy              0.13.1
py                  1.9.0
pyparsing           2.4.7
pytest              6.1.0
setuptools          47.1.0
six                 1.15.0
toml                0.10.1
```

If you need more info I can provide the file too.  Thanks!

**Comment by sfc-gh-gbutzi** [comment]
This issue is mostly resolved.

The exception happens because the diagram parser would find the trust boundary, not be able to get the trust zone of it, and break. The diagram parser can now examine objects it doesn't expect to see (e.g. trust boundaries and STRIDE labels) and discard them without breaking, continuing to parse the rest of the diagram.

If you hadn't run into that issue, you would have found two other issues: you have data flowing between entities without an intermediary process, and you have bidirectional flows. Those issues are still extant in the code, but are easy to correct by hand if you know they exist - I added some details to the readme to clarify what a correct (parseable) DFD should look like.

With a slightly redrawn diagram to fix those issues, it parses correctly and without issue. I'm going to close this issue and open two more to address the outstanding problems in the future.
